# Site
repository: kapiresz/kapiresz.github.io
favicon: images/favicon.ico

# Personal info
name: Markos Hay
title: Full-time Student & Aspiring Project Manager
email: markoshay902@gmail.com
website: ccproject.info

# Social links
#twitter_username: facespics
github_username:  kapiresz
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: markoshay
linkedin_username: markoshay
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Markos and I'm a final year student at Nottingham Business School, NTU and founder (and Consultant) of CCProject.info. Outgoing, detail-orientated, an efficient problem solver who is curious and eager to learn with a commitment to pursue a career in Consulting & Business Development. Driven by results, strives for excellence, pushes boundaries by conquering fears and passionate about making a difference.

  I am most skilled in: <mark>Leadership</mark> and <mark>Problem Solving</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Business and Consulting some of my other interests and hobbies are:
   - Photography, both analog and digital
   - Gaming
   - Cooking
   - Travelling
   - Tennis
   - Rock Climbing
#  - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
darkmode: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
